= Eclipse uProtocol client vsomeip python
:toc:

Python uPClient implementation for SOME/IP using vsomeip

== Overview

Python module to leverage someip implementations developed from other programming languages.


== Getting Started

=== Prerequisites
Download, Build, and Install vsomeip - [COVESA / vsomeip](https://github.com/COVESA/vsomeip)
for windows support: [COVESA / vsomeip (fork)](https://github.com/justinlhudson/vsomeip)

==== Linux
1. clone vsomeip repo https://github.com/COVESA/vsomeip.
2. Follow Build instructions for Linux on the GitHubPage: https://github.com/COVESA/vsomeip
	a. sudo apt-get install asciidoc source-highlight doxygen graphviz
	b. sudo apt-get install libboost-all-dev
	c. sudo apt install cmake
3. open a terminal window at vsomeip directory.
4. mkdir build
5. cd build
6. cmake ..
7. make
8. sudo make install

[!TIP]
'error' loading configuration module
sudo ldconfig

==== Windows
1. Install boost - https://sourceforge.net/projects/boost/files/boost-binaries/1.65.0/boost_1_65_0-msvc-14.1-64.exe/download
2. Install Visual Studio - With Development with C++ options
3. Clone the forked vsomeip repo https://github.com/justinlhudson/vsomeip
4. Open the local folder vsomeip in Visual Studio
5. Right click on cmakeLists.txt and click Build - generates build files in a folder called out -> build -> x64-Debug (dll files)
6. Right click on cmakeLists.txt and click Install
7. Copy libs from build folder to Install Lib folder
8. From Number 5, Rename x64-Debug folder to vsomeip and move it to C drive
9. Copy dlls in C:\local\boost_1_65_0\lib64-msvc-14.1 to C:\Windows\System32
10. Copy dlls in C:\Users\<vsomeip_cloned_path>\out\install\vsomeip\bin to C:\Windows\System32

vsomeip Directory structure:
----
>      ├── vsomeip
>      │   ├── bin
>      │   ├── include
>      │   ├── lib
>      │   ├── etc
>      │   ├── ...
----


=== Importing the up-client-vsomeip-python

Set up up-client-vsomeip-python local repository and install
[source]
----
$ git clone https://github.com/eclipse-uprotocol/up-client-vsomeip-python.git
$ python setup.py bdist_wheel
----
*This will generate the wheel file to install/import for using vsomeip python client.*

=== Usage

$ pip install uprotocol_vsomeip_python-0.1-py3-none-any.whl

uPClient vsomeip Transport

[source]
----
from uprotocol_vsomeip.vsomeip_utransport import VsomeipTransport
from uprotocol_vsomeip.vsomeip_utransport import VsomeipHelper

# Create a helper class and override the services_info method to set the mock services to be run by Vsomeip
class Helper(VsomeipHelper):

    def services_info(self) -> List[VsomeipHelper.UEntityInfo]:
        return [VsomeipHelper.UEntityInfo(Name="body.cabin_climate", Id=5)]

# Create an object of Vsomeip transport to use and pass on the above helper class created
someip = VsomeipTransport(helper=Helper())
----

==== Publish/Subscribe

[source]
----
def publish():
    protoobj = cabin_climate_topics_pb2.Zone()
    protoobj.fan_speed = 4
    protoobj.is_power_on = True
    any_obj = any_pb2.Any()
    any_obj.Pack(protoobj)
    payload_data = any_obj.SerializeToString()
    payload = UPayload(value=payload_data, format=UPayloadFormat.UPAYLOAD_FORMAT_PROTOBUF)

    u_authority = UAuthority(name="myremote", ip=socket.inet_aton(socket.gethostbyname(socket.gethostname())))
    u_entity = UEntity(name='body.cabin_climate', id=5, version_major=1, version_minor=1)
    u_resource = UResource(name="zone", instance="row1_left", message="Zone", id=3)
    uri = UUri(authority=u_authority, entity=u_entity, resource=u_resource)
    attributes = UAttributesBuilder.publish(uri, UPriority.UPRIORITY_CS0).build()
    someip.send(UMessage(attributes=attributes, payload=payload))


class myListener(UListener):
    def on_receive(self, message: UMessage):
        print(f"listener -> id: {message.attributes.source.resource.id}, data: {message.payload.value}")


def subscribe():
    u_authority = UAuthority(name="myremote", ip=socket.inet_aton(socket.gethostbyname(socket.gethostname())))
    u_entity = UEntity(name='body.cabin_climate', id=5, version_major=1, version_minor=1)
    u_resource = UResource(name="zone", instance="row1_left", message="Zone", id=3)
    uri = UUri(authority=u_authority, entity=u_entity, resource=u_resource)
    listener1 = myListener()
    someip.register_listener(uri, listener1)


if __name__ == '__main__':
    publish()
    time.sleep(1)
    subscribe()
    time.sleep(1)
----

==== RPC

[source]
----
class RPCRequestListener(UListener):
    def on_receive(self, umsg: UMessage):
        print('on rpc request received')
        attributes_response = UAttributesBuilder.response(umsg.attributes.sink,
                                                          umsg.attributes.source,
                                                          UPriority.UPRIORITY_CS4,
                                                          Factories.UPROTOCOL.create()).build()
        message = UMessage(attributes=attributes_response, payload=umsg.payload)
        someip.send(message)


def service():
    u_entity = UEntity(name='chassis.braking', id=17, version_major=1, version_minor=0)
    u_resource = UResourceBuilder.for_rpc_request("ResetHealth", id=1)

    sink = UUri(entity=u_entity, resource=u_resource)
    listener = RPCRequestListener()
    someip.register_listener(sink, listener)


def client():
    hint = UPayloadFormat.UPAYLOAD_FORMAT_PROTOBUF
    any_obj = any_pb2.Any()
    reset_request = braking_service_pb2.ResetHealthRequest(name="brake_pads.front")
    any_obj.Pack(reset_request)
    payload_data = any_obj.SerializeToString()
    payload = UPayload(value=payload_data, format=hint)
    u_entity = UEntity(name='chassis.braking', id=17, version_major=1, version_minor=0)
    u_resource = UResourceBuilder.for_rpc_request("ResetHealth", id=1)
    method_uri = UUri(entity=u_entity, resource=u_resource)

    res_future = someip.invoke_method(method_uri, payload, CallOptions())

    while not res_future.done():
        time.sleep(1)

    print("FUTURE RESULT", res_future.result())


if __name__ == '__main__':
    service()
    time.sleep(1)
    client()
    time.sleep(1)
----